### PR TITLE
Feature/nextjs migration

### PR DESCRIPTION
**Pull request by DevPH-Wistkey**
1. Completely migrated to Next.Js
2. Change component to Next.Js component (e.g Image)
3. Wallet functionality migrated to Next.Js
4. Fixing error on build (array initialization, downLevelIteration)

RUN:
1. Development: yarn dev
2. Build: yarn build -> yarn start

### CODE REVIEW

**Comment by tralkan** [comment]
Hi, thanks so much for this PR! What do you mean with

> 3. Wallet functionality migrated to Next.Js

?

**Comment by DevPH-Wistkey** [comment]
> Hi, thanks so much for this PR! What do you mean with
> 
> > 3. Wallet functionality migrated to Next.Js
> 
> ?

Great! On previous PR Connect wallet features(ZilPay, SSI) haven't migrated yet. But now, all that feature are finished migrated to Next.js

**Comment by DevPH-Wistkey** [comment]
Search bar animation: worked and tested on build

**Review by tralkan — CHANGES_REQUESTED** [review]
Hi, it is unnecessary to create a new store for the username since it is already in the user store, field name. Also, unfortunately, it is not as easy as changing PublicIdentity for the username itself. The goal here is that when you do "ssibrowser.com/yourname", it takes you to your identity, which is not the case now. Please review.

**Comment by tralkan** [comment]
Thank you, guys! Some things still missing are:
- The landing page's transition for the background (thunder falling) and search bar opening.
- Fixing the position of the logos
image

Thanks!

**Pull request merged**
