### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DevPH-Wistkey**
@tralkan

### CODE REVIEW

**Comment by tralkan** [comment]
Hi @DevPH-Wistkey can you revert the commit on zilpay-base? it doesn't add any new logic, right?

**Comment by DevPH-Wistkey** [comment]
Sure, done revert zilpay-base @tralkan

**Review by tralkan — APPROVED** [review]

**Comment by tralkan** [comment]
to fix merging conflicts, try running prettier on zilpay-base and pushing to this PR @DevPH-Wistkey

**Comment by DevPH-Wistkey** [comment]
done @tralkan

**Pull request merged**
